### ISSUE TITLE
when set a scaling rate of the screen，the capture area is incorrect

### ISSUE THREAD

**Issue by lazytao** [adrian-andersson/psScreenRecorder#1]
when set the screen scaling rate to 150%，the captured area is only two-thirds of the original

**Comment by adrian-andersson** [comment]
Fixed in 1.0.6
![scale](https://user-images.githubusercontent.com/31834645/54408765-4bae5380-4737-11e9-9f8a-78d6e8c7797e.gif)

**Comment by adrian-andersson** [comment]
As per comment

**Comment by lazytao** [comment]
sorry, but there may be several new bugs here.
at first, the dpi type can't find, but after copy it from the source file and excute it, it works, it seems that the line 620 in psScreenRecorder.psm1 is not being executed.
secondly, when scalling rate is set, the cursor position is incorrect.

**Comment by adrian-andersson** [comment]
Thanks for the feedback, I'll take a look and get it sorted.

**Comment by adrian-andersson** [comment]
@lazytao I've redone how the typedef is checked and loaded, should be ok now
I've also applied the scale to the mouse-cursor
I tested it on my machine on 100,125,150,175, it turned out ok for all scenarios.

All fixes should be in 1.0.7. If you could let me know if this is resolved that would be fantastic. Thanks for helping, I don't use scaling myself so never noticed the requirement.

**Comment by lazytao** [comment]
I tried it and the problem has been solved. That's cool.
